/* this is a file autogenerated by spice_codegen.py */
/*
  Copyright (C) 2013 Red Hat, Inc.

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, see <http://www.gnu.org/licenses/>.
*/

#ifndef _H_SPICE_ENUMS
#define _H_SPICE_ENUMS

enum {
    SPICE_CHANNEL_MAIN = 1,

    SPICE_END_CHANNEL
};

enum {
    SPICE_MSG_MAIN_SHORTDATASUBMARSHALL = 1,
    SPICE_MSG_MAIN_ARRAYMESSAGE,
    SPICE_MSG_MAIN_ZEROES,
    SPICE_MSG_MAIN_CHANNELS_LIST,
    SPICE_MSG_MAIN_LENMESSAGE,
    SPICE_MSG_MAIN_ZEROLEN1,

    SPICE_MSG_END_MAIN
};

#endif /* _H_SPICE_ENUMS */
